* PSI Energy
** Generic Fluff
*** Info power
**** Generated by Information processing
     Includes any life
     Especially includes things with nervous systems
**** Resonant materials can handle the energy
     Organic material is bad at storing vibrations, but quick to generate them
***** Materials for picking up vibrations
      Crystals?
***** Materials for transmitting vibrations
      Crystals?

** Mechanics
*** TODO Energy network
**** Collectors
     Directly absorb from nearby players
     Computational engines to generate independently?
**** Effectors
**** Transmission
     Intermediate nodes of some kind
     Link nodes together (collectors > transmitters > effectors) wirelessly (range limit?)
     Source and target can be anything that conducts energy (though a collector may not necessarily
     pass on upstream energy)
     Either the source must have no existing incoming connections, or the target must not have
     outgoing connections
     This forces a DAG structure
**** Implementation
     Collectors, Effectors, Transmission nodes, etc. are all one kind of thing (call them shuttlers)

     Transducer nodes need a "pull" function

     Pull function is for taking units of energy. Takes request amount, requester node,
     position of requester,
     as arguments, returns the amount actually extracted

     Position argument only really important for graphical effects. Node argument useful for
     accessing metadata

     Return value is useful to limit energy rate.

     Transducer nodes contain upstream nodes in their metadata
***** Examples
      Energy generator (Collector) - has some internal energy buffer (in metadata) that is incremented on ABM. When
      energy is requested, it subtracts that amount from the buffer and returns it

      Transmitter node - When energy is requested, tries to pull from upstream nodes until the desired
      amount is obtained
     
      Dirt generator (Effector) - has internal energy buffer like collector, but pulls from network on ABM.
      When it fills the buffer, it creates a piece of dirt and resets the buffer to 0.
